export const userTypes = {
  USER_LOGIN: "USER_LOGIN",
  USER_AUTH_CHECK: "USER_AUTH_CHECK",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  USER_DELETE: "USER_DELETE",
  USER_UPDATE: "USER_UPDATE",
};
